// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package keyval

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[String-0]
	_ = x[Float-1]
	_ = x[Int-2]
	_ = x[Date-3]
	_ = x[SliceStr-4]
	_ = x[SliceFloat-5]
	_ = x[SliceInt-6]
	_ = x[SliceDate-7]
	_ = x[InValid-8]
}

const _DataType_name = "StringFloatIntDateSliceStrSliceFloatSliceIntSliceDateInValid"

var _DataType_index = [...]uint8{0, 6, 11, 14, 18, 26, 36, 44, 53, 60}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
